// Date: 22.5.2014 16:53:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package celestialwizardry.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOreGolem extends ModelBase
{
  //fields
    ModelRenderer l3;
    ModelRenderer l2;
    ModelRenderer l1;
    ModelRenderer l0;
    ModelRenderer r3;
    ModelRenderer r2;
    ModelRenderer r1;
    ModelRenderer r0;
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer base3;
    ModelRenderer base4;
    ModelRenderer part1;
    ModelRenderer part2;
    ModelRenderer part3;
    ModelRenderer part4;
  
  public ModelOreGolem()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      l3 = new ModelRenderer(this, 0, 0);
      l3.addBox(0F, 0F, 0F, 3, 3, 3);
      l3.setRotationPoint(6F, 17F, -1F);
      l3.setTextureSize(64, 32);
      l3.mirror = true;
      setRotation(l3, -0.8702405F, 0.5801603F, 2.416392F);
      l2 = new ModelRenderer(this, 0, 0);
      l2.addBox(0F, 0F, 0F, 3, 3, 3);
      l2.setRotationPoint(4F, 20F, -1F);
      l2.setTextureSize(64, 32);
      l2.mirror = true;
      setRotation(l2, -0.3626002F, 0.9790205F, 2.973322F);
      l1 = new ModelRenderer(this, 0, 0);
      l1.addBox(0F, 0F, 0F, 3, 3, 3);
      l1.setRotationPoint(4F, 19F, -1F);
      l1.setTextureSize(64, 32);
      l1.mirror = true;
      setRotation(l1, 0.2175601F, -0.2900802F, 0.4713802F);
      l0 = new ModelRenderer(this, 0, 0);
      l0.addBox(0F, 0F, 0F, 3, 3, 3);
      l0.setRotationPoint(4F, 20F, -1F);
      l0.setTextureSize(64, 32);
      l0.mirror = true;
      setRotation(l0, -0.6164203F, 0.6889404F, 0.5439003F);
      r3 = new ModelRenderer(this, 0, 0);
      r3.addBox(0F, 0F, 0F, 3, 3, 3);
      r3.setRotationPoint(-3F, 17F, 3F);
      r3.setTextureSize(64, 32);
      r3.mirror = true;
      setRotation(r3, -0.8702405F, -1.124061F, 2.416392F);
      r2 = new ModelRenderer(this, 0, 0);
      r2.addBox(0F, 0F, 0F, 3, 3, 3);
      r2.setRotationPoint(-3F, 20F, 2F);
      r2.setTextureSize(64, 32);
      r2.mirror = true;
      setRotation(r2, -0.3626002F, -1.631701F, 2.973322F);
      r1 = new ModelRenderer(this, 0, 0);
      r1.addBox(0F, 0F, 0F, 3, 3, 3);
      r1.setRotationPoint(-3F, 19F, 2F);
      r1.setTextureSize(64, 32);
      r1.mirror = true;
      setRotation(r1, 0.2175601F, -3.141593F, 0.4713802F);
      r0 = new ModelRenderer(this, 0, 0);
      r0.addBox(0F, 0F, 0F, 3, 3, 3);
      r0.setRotationPoint(-4F, 20F, -1F);
      r0.setTextureSize(64, 32);
      r0.mirror = true;
      setRotation(r0, -0.6164203F, -2.792022F, 0.5439003F);
      base1 = new ModelRenderer(this, 0, 6);
      base1.addBox(0F, 0F, 0F, 5, 5, 5);
      base1.setRotationPoint(6F, 10F, 0F);
      base1.setTextureSize(64, 32);
      base1.mirror = true;
      setRotation(base1, 1.305361F, -2.103081F, 1.958041F);
      base2 = new ModelRenderer(this, 0, 6);
      base2.addBox(0F, 0F, 0F, 5, 5, 5);
      base2.setRotationPoint(1F, 12F, -2F);
      base2.setTextureSize(64, 32);
      base2.mirror = true;
      setRotation(base2, 0.3988602F, -0.5076403F, 1.958041F);
      base3 = new ModelRenderer(this, 0, 6);
      base3.addBox(0F, 0F, 0F, 5, 5, 5);
      base3.setRotationPoint(2F, 9F, 4F);
      base3.setTextureSize(64, 32);
      base3.mirror = true;
      setRotation(base3, -0.7252004F, -1.341621F, 1.01528F);
      base4 = new ModelRenderer(this, 0, 6);
      base4.addBox(0F, 0F, 0F, 5, 5, 5);
      base4.setRotationPoint(2F, 15F, -5F);
      base4.setTextureSize(64, 32);
      base4.mirror = true;
      setRotation(base4, 2.356901F, -2.320641F, 0.2726269F);
      part1 = new ModelRenderer(this, 0, 0);
      part1.addBox(0F, 0F, 0F, 3, 3, 3);
      part1.setRotationPoint(0F, 10F, -4F);
      part1.setTextureSize(64, 32);
      part1.mirror = true;
      setRotation(part1, -1.667961F, 1.921781F, -0.3263402F);
      part2 = new ModelRenderer(this, 0, 0);
      part2.addBox(0F, 0F, 0F, 3, 3, 3);
      part2.setRotationPoint(2F, 11F, -2F);
      part2.setTextureSize(64, 32);
      part2.mirror = true;
      setRotation(part2, -0.1450401F, 1.885521F, -1.051541F);
      part3 = new ModelRenderer(this, 0, 0);
      part3.addBox(0F, 0F, 0F, 3, 3, 3);
      part3.setRotationPoint(0F, 11F, -4F);
      part3.setTextureSize(64, 32);
      part3.mirror = true;
      setRotation(part3, -0.7977204F, 1.921781F, -1.559181F);
      part4 = new ModelRenderer(this, 20, 0);
      part4.addBox(0F, 0F, 0F, 4, 4, 4);
      part4.setRotationPoint(-3F, 8F, -6F);
      part4.setTextureSize(64, 32);
      part4.mirror = true;
      setRotation(part4, -0.2538201F, 0.3626002F, -0.5801603F);
  }
  
  public void render(Entity entity, float f0, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f0, f1, f2, f3, f4, f5);
    setRotationAngles(f0, f1, f2, f3, f4, f5, entity);
    l3.render(f5);
    l2.render(f5);
    l1.render(f5);
    l0.render(f5);
    r3.render(f5);
    r2.render(f5);
    r1.render(f5);
    r0.render(f5);
    base1.render(f5);
    base2.render(f5);
    base3.render(f5);
    base4.render(f5);
    part1.render(f5);
    part2.render(f5);
    part3.render(f5);
    part4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f0, float f1, float f2, float f3, float f4, float f5, Entity ent)
  {
    super.setRotationAngles(f0, f1, f2, f3, f4, f5, ent);
  }

}
